# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-24 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, upload_to='products/', verbose_name='Изображение ткатегории')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Категории',
                'verbose_name': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='GObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='Слаг')),
                ('date_of_event', models.CharField(db_index=True, max_length=200, verbose_name='Дата')),
                ('place', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('location_x', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Широта')),
                ('location_y', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Долгота')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Изображение')),
                ('site', models.CharField(db_index=True, max_length=200, verbose_name='Сайт')),
                ('fb_group', models.CharField(db_index=True, max_length=200, verbose_name='Фейсбук')),
                ('vk_group', models.CharField(db_index=True, max_length=200, verbose_name='Вконтакте')),
                ('tw_chanel', models.CharField(db_index=True, max_length=200, verbose_name='Твиттер')),
                ('inst_chanel', models.CharField(db_index=True, max_length=200, verbose_name='Инстаграм')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='data.GCategory', verbose_name='Категория')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Товары',
                'verbose_name': 'Товар',
            },
        ),
        migrations.AlterIndexTogether(
            name='gcategory',
            index_together=set([('id', 'slug')]),
        ),
        migrations.AlterIndexTogether(
            name='gobject',
            index_together=set([('id', 'slug')]),
        ),
    ]
