# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-24 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20170224_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gobject',
            name='place',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Локация'),
        ),
    ]
