# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-24 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20170224_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcategory',
            name='icon',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='Изображение категории'),
        ),
    ]
