# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-24 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20170225_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gobject',
            name='location_x',
        ),
        migrations.RemoveField(
            model_name='gobject',
            name='location_y',
        ),
    ]
