# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-24 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20170225_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gobject',
            name='date_of_event',
        ),
        migrations.RemoveField(
            model_name='gobject',
            name='fb_group',
        ),
        migrations.RemoveField(
            model_name='gobject',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gobject',
            name='inst_chanel',
        ),
        migrations.RemoveField(
            model_name='gobject',
            name='place',
        ),
        migrations.RemoveField(
            model_name='gobject',
            name='site',
        ),
        migrations.RemoveField(
            model_name='gobject',
            name='tw_chanel',
        ),
        migrations.RemoveField(
            model_name='gobject',
            name='vk_group',
        ),
    ]
