# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-24 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20170225_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='gobject',
            name='date_of_event',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='gobject',
            name='fb_group',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Фейсбук'),
        ),
        migrations.AddField(
            model_name='gobject',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='gobject',
            name='inst_chanel',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Инстаграм'),
        ),
        migrations.AddField(
            model_name='gobject',
            name='location_x',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='gobject',
            name='location_y',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='gobject',
            name='place',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='gobject',
            name='site',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Сайт'),
        ),
        migrations.AddField(
            model_name='gobject',
            name='tw_chanel',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Твиттер'),
        ),
        migrations.AddField(
            model_name='gobject',
            name='vk_group',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Вконтакте'),
        ),
    ]
