# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20161013_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='miniDescription',
            field=models.TextField(blank=True, max_length=255, verbose_name='Краткое Описание'),
        ),
    ]
