# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-22 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_product_minidescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_side2',
            new_name='image_back',
        ),
        migrations.AlterField(
            model_name='product',
            name='image_side',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='Изображение товара сбоку'),
        ),
    ]
