# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-22 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20170122_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parameter',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Параметр'),
        ),
        migrations.AddField(
            model_name='product',
            name='parameter_value',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='значение параметра'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_back',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='Изображение сзади'),
        ),
    ]
