# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20170208_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='Иконка категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Имя'),
        ),
    ]
