# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20170213_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterIndexTogether(
            name='category',
            index_together=set([]),
        ),
    ]
