# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20170213_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
