# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20170213_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='second_parameter',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Параметр'),
        ),
        migrations.AddField(
            model_name='product',
            name='second_parameter_value',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='значение параметра'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
    ]
