# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_auto_20170213_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
