# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_category_main_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='Изображение товара'),
        ),
    ]
