# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-15 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='main_name',
        ),
    ]
