# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-01 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_auto_20170216_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_rub',
            field=models.DecimalField(blank=True, decimal_places=2, default='1', max_digits=10, verbose_name='Цена рубли'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='Изображение ткатегории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='parameter',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Параметр'),
        ),
        migrations.AlterField(
            model_name='product',
            name='parameter_value',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='значение параметра'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена белрубли'),
        ),
        migrations.AlterField(
            model_name='product',
            name='second_parameter',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Параметр'),
        ),
        migrations.AlterField(
            model_name='product',
            name='second_parameter_value',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='значение параметра'),
        ),
    ]
