# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.CharField(max_length=250, null=True, verbose_name='Время'),
        ),
    ]
