# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.CharField(max_length=250, null=True, verbose_name='В какое время доставить товар?'),
        ),
    ]
