# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20161121_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated',
        ),
    ]
